### ISSUE TITLE
`eigenlayer rewards show` returns incorrect Strategy data

### ISSUE THREAD

**Issue by brandoncurtis** [Layr-Labs/eigenlayer-cli#199] opened 2024-08-21 17:43 UTC
**Describe the bug**
`eigenlayer rewards show` attributes Strategies incorrectly for Operators with rewards from multiple Strategies

**To Reproduce**
```
$ eigenlayer rewards show --earner-address 0x4cd2086e1d708e65db5d4f5712a9ca46ed4bbd0a --network mainnet
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Strategy Address                           | AVS Address                                | Token Address                              | Wei Amount                                
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 11012959952785484
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0xae60d8180437b5c34bb956822ac2710972584473 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
$ eigenlayer rewards show --earner-address 0x4cd2086e1d708e65db5d4f5712a9ca46ed4bbd0a --network mainnet
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Strategy Address                           | AVS Address                                | Token Address                              | Wei Amount                                
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 11012959952785484
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
0x0fe4f44bee93503346a3ac9ee5a26b130a5796d6 | 0x870679e138bcdf293b7ff14dd44b70fc97e12fc0 | 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 | 2293639671261070
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```
**Expected behavior**
Should correctly attribute the strategy to the earned rewards; instead it seems to grab the strategy from the first line of rewards that's returned and duplicate that across all lines.  The return will change if you run it a few times in a row.

**Version details**
- Linux
- `eigenlayer-cli` v0.10.2

**Comment by shrimalmadhur** [comment] 2024-08-21 18:05
We have root caused this. will update once the fix has landed.

**Closed** 2024-08-26 16:19 UTC
Labels: bug
